### ISSUE TITLE
Cannot download from Baidu

### ISSUE THREAD

**Issue by JBKnights** [MetaSLAM/GPR_Competition#12]
Hi,

I'm currently trying to download the dataset in Australia - I cannot register an account for Baidu or navigate the interface, and the dropbox link still appears to be broken.  Is there a timeline on when this issue will be fixed?

Thank you,

Joshua

**Comment by maxtomCMU** [comment]
Hi all, all the dropbox and Baidu pan links have been updated, please take a look at the readme.
