### ISSUE TITLE
Unable to extract the dataset

### ISSUE THREAD

**Issue by sudarshan-s-harithas** [MetaSLAM/GPR_Competition#13]
I am unable to extract the files TRAIN.tar.gz.00 , TRAIN.tar.gz.01 , TRAIN.tar.gz.02  for the  3D-3D LiDAR scan dataset given in this [link](https://www.dropbox.com/sh/q1w5dmghbkut553/AAAsS8F_QZ_QPVyzMpkzF66ea/UGV?dl=0&subfolder_nav_tracking=1), can you please help me with this. 

Thank You

**Comment by maxtomCMU** [comment]
Hi @sudarshan-s-harithas, is the problem still there? 

Hi @ryanzhao9459, can we verify this?

**Comment by sudarshan-s-harithas** [comment]
Hi, Yes I am still facing the issue. 

From the link given above, I downloaded the files and tried to decompress it. It failed.

**Comment by ryanzhao9459** [comment]
Hi, please try this command
`cat TRAIN.tar.gz.* | tar -zxv`

**Comment by sudarshan-s-harithas** [comment]
It does not seem to extract with this command the error is as shown below 

gzip: stdin: not in gzip format
tar: Child died with signal 13
tar: Error is not recoverable: exiting now

**Comment by ryanzhao9459** [comment]
That's weird, I have double checked the command on my side and it goes well. Maybe, try to download dataset again in case of file corruption?
