### ISSUE TITLE
UAV round 2 dataset - gt_matches.csv in train subset is missing

### ISSUE THREAD

**Issue by metra4ok** [MetaSLAM/GPR_Competition#16]
There is no `gt_matches.csv` for `Train` subset of UAV dataset for round 2:

```
$ ls Train/
query.csv  query_images  reference.csv  reference_images

$ ls Val/
gt_matches.csv  query.csv  query_images  reference.csv  reference_images
```

Can you provide this file? Thank you!

**Comment by ryanzhao9459** [comment]
Sorry for the late reply. gt_matches.csv is available now. Please go to Dropbox for downloading.
