### ISSUE TITLE
Error in visualize cloud

### ISSUE THREAD

**Issue by qq1962572025** [MetaSLAM/GPR_Competition#18]
I try to use the pose in npy file to visualize database and query clouds. In round 1, the paired point clouds are successfully displayed in picture above. However, in round 2, the point clouds show a clear deviation in picture below. I guess there is a mismatch between pose and point cloud
![image](https://user-images.githubusercontent.com/40595559/177683472-aa7dfa59-4c8e-4b05-bb3c-308c281387e7.png)
![image](https://user-images.githubusercontent.com/40595559/177683490-e49e7a33-ad6b-4935-abeb-d38b90faa7fb.png)

**Comment by ryanzhao9459** [comment]
It will be appreicated if u could specify which track in the validation set. And I will check that out.

**Comment by qq1962572025** [comment]
> It will be appreicated if u could specify which track in the validation set. And I will check that out.

![image](https://user-images.githubusercontent.com/40595559/178674165-ed8b670a-b05d-463e-9163-518d608c29ec.png)
I try almost every sequence in round 2, each of them has problem. Above is between VAL_ROUND_2/VAL/val_6/QUERY/rot_180 and VAL_ROUND_2/VAL/val_6/DATABASE. Clouds from the same sequence are tranformed to world coordinates and are added together.

After I tranform gt pose intp txt format, I use this code to get the pose matrix:
std::stringstream ss(line);
            std::vector<double> data(7, 0);
            if (!line.empty()) {
                for (int i = 0; i < 7; i++)
                    ss >> data[i];
            }
            Eigen::Isometry3d pose(Eigen::Isometry3d::Identity());
            Eigen::Matrix3d rot(Eigen::AngleAxisd(data[3], Eigen::Vector3d::UnitX())
            *Eigen::AngleAxisd(data[4], Eigen::Vector3d::UnitY()) *
            Eigen::AngleAxisd(data[5], Eigen::Vector3d::UnitZ()));
            Eigen::Vector3d trans(data[0], data[1], data[2]);
            pose.prerotate(rot);
            pose.pretranslate(trans);
            poses.push_back(pose);

**Comment by ryanzhao9459** [comment]
Ok, I will check the data.

**Comment by ryanzhao9459** [comment]
![val_6](https://user-images.githubusercontent.com/47678677/178773851-0ff8b002-a8c2-4067-93d6-0309c0349f7b.png)
I have double checked the data, and the outcome looks fine.
I notice that the rotation matrix is generated by using the functions for Euler Angles in your method. But the pose data we provide is given in Rotation Vector which is stated in readme.

**Comment by ryanzhao9459** [comment]
Maybe u could try changing the functions and see how does it work.

**Comment by qq1962572025** [comment]
> Maybe u could try changing the functions and see how does it work.

I have changed the code. Result looks nice.
![image](https://user-images.githubusercontent.com/40595559/179002668-d3dac96c-b3d4-4310-9b6e-f2569f01b8af.png)
I have another problem. Clouds in round2 is downsampled to less than 5000 points. The number is too fewer for some algorithms.  Will the full dataset include denser point clouds?

**Comment by ryanzhao9459** [comment]
Yes, all the point clouds are downsampled to 4096 points.

**Comment by ryanzhao9459** [comment]
> > Maybe u could try changing the functions and see how does it work.
> 
> I have changed the code. Result looks nice. ![image](https://user-images.githubusercontent.com/40595559/179002668-d3dac96c-b3d4-4310-9b6e-f2569f01b8af.png) I have another problem. Clouds in round2 is downsampled to less than 5000 points. The number is too fewer for some algorithms. Will the full dataset include denser point clouds?

Yes, all the point clouds are downsamples to 4096 points for round 2. The full dataset will be released after the competition with our ongoing dataset paper.
