### ISSUE TITLE
When will datasets be available for download？

### ISSUE THREAD

**Issue by zdw-qingdao** [MetaSLAM/GPR_Competition#6]
I am willing to take part in the competition. Could you tell me when will datasets be available for download？
Thanks！

**Comment by maxtomCMU** [comment]
Hi, the datasets and evaluation api will be ready in next month. Please keep tracking this issue, thanks for your interests.

**Comment by HaowenLai** [comment]
@zdw-qingdao Hello, we now provide sample data for the **Pittsburgh City-scale Dataset**, and you can find it [here](https://sandbox.zenodo.org/record/1033096). For a quick start, please refer to `test/test_pitts.py` and `test/test_pitts.ipynb`.

Please feel free to report any other issue. Thanks.

**Comment by JimPlayboy** [comment]
> @zdw-qingdao Hello, we now provide sample data for the **Pittsburgh City-scale Dataset**, and you can find it [here](https://sandbox.zenodo.org/record/1033096). For a quick start, please refer to `test/test_pitts.py` and `test/test_pitts.ipynb`.
> 
> Please feel free to report any other issue. Thanks.

@HaowenLai hello, the sample data doesn't work

**Comment by JimPlayboy** [comment]
> @zdw-qingdao Hello, we now provide sample data for the **Pittsburgh City-scale Dataset**, and you can find it [here](https://sandbox.zenodo.org/record/1033096). For a quick start, please refer to `test/test_pitts.py` and `test/test_pitts.ipynb`.
> 
> Please feel free to report any other issue. Thanks.

@HaowenLai hello, the sample data doesn't work

**Comment by maxtomCMU** [comment]
Hi @JimPlayboy , the above issues have been fixed, please take a look at the readme.
